os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
    - ARCH=x86_64 DISTRIB=debian
    - ARCH=x86_64 DISTRIB=alpine
#    - ARCH=armhf DISTRIB=debian
    - ARCH=armhf DISTRIB=alpine
  global:
  - secure: f/NmBF9YdA9KOUesjM/RN4TmKKhXyNypHsV9TDkdwsxyNzSWLSDq4HYARUGR8TZ/5fD3ZNI1V+xL+iKsWdvPToFVt4R3dvvLWtWOXXGosbuF8e/B/KRKOvrJIdsHn4m5CU9P3pfs8pIzFrlhH2NKxLJID9gV27hoNxCb1xh4vAEuz8uBZNROycSsjk2u33ca2UelXXaDtxVMjY/SeHYJd0QqTwkLKYp10tHwvo6zSFtf72VSaImlqDxSNqcHsGAs2Okg1QlK3khujPg7vI+xCAxi3fun9TJzN3j+DSnCmUqhprZE7Vr+iuev0QlIy04sP2k2jMMbwYOOoVbIn9/v1fUsgH9WfsOSJf/pyXRULzgcpt07kW0aB2g2Gm4fefu8SpTedX5blFZSglsA9uzczV6gUJ5tPGQWsokOTjaLZh2Wl+12Ql80gro83kbF8FjeIxLGK9FmS72raVQ930Kevdnvw6aHE2+ppTMuYcs7ifW1DMg2RVteVqeYypESRKRgQNRtAWpdDO0aIWYW0i5Ec0XH39EPmyK3K75oio4Kf1BHRwBNyRzuf1DvRMDBWltARlfIh5Qk2JCyl7pfIemot8pjyABEykzm21DUv2bDiqRhvgZqDHCOCF/wBuZSVU0MpI4Oceg9bsCPDXSOH4xRbCAlI6TMxttVvPfofXuX5hE=
  - secure: KlklDV1jTim8wjWNHqSzfB7pMSB/4Y0S2lYdQzRQ4LhAcrK7XahXd1kWVXXNasFD6c3fgImSeIZLsYb289p1G4tsmR0CZX5KkerdmsNzKCUR6Srk7DkL3DU/aYaX/XuvG0Gh8I0Zok73oTKiS72vcsBZuvn3Q1q1hU07gwEPVEOd0WpEHlNZ5NB4MPTc0QnXCmiOq/XM5AlX27Ct3aMbqXQRP/fZKP6V7C0a/OpB2h6PIEjvIWRwA4RUCub9KVp81Ze5GHyQKo/9wPRyl0RvrAO2gfDWJwh/e5GIGUjt5E170JpfUnG6nSot+cv43FouGftqitKWtf6DE+YEEOOeqsS/rNma5wS6WjYeKa5yTeN+LX1dCcUIoX21VJ9lL4JFtxrF/oZErlo8kGC32XyvFBLHRSsBXDHCSBpCoSIY6/vNeVFPcV90TbEHL7Shv0EUgwvdfkrHXYhhYDiD9j2DmGWbbcWmVCcPN1vJiAdb7Fwsnxz0qDUNli7vZdFjkMsMYLMN5Bc02FJccujyDVe5z4ZU4wDWM50Xto+xFhvYl7NN4inwhgR27B/Tvqeay6YBXx2PgyFVB9hZT6LoqupBKd+wCSn0QcjqCsj6eSjpjUrnjTA49d3WLFRrUvQike+tTTenOTQa+eZfn1x48IsHtVMT9rspJ0vBU/vNG/vw97c=
  - secure: UvDQLFXoip2dHY16Hrwbqd7uKe8cIswBPJ2jzM5wXuQxpOYZgPCvpM0WSDYhE8fJbNKsWSRLK2YJz3LrgkeIQiQqU4l1euPqab3/6HAiwuseMf4sp2m3jAPxw7g63FoK6YitDeQDCZuorNe+cFMr0leI817Ovryl/7zFLSmHE7yQUOuGojSUBUHqwNSDWfKqNOMWpaBr6UYivs5or3BI0s5dNtKr8K4vUot/1tDHyb4qd4vQqMr1Z96HbL87e69vhqwzWT0p917JIIjQIfvQEtkzKpa8Fj6aWL9R8vOREePk+YzjHUxT8k64uJwnlCNsi/KXe8FMcF3lRUXqZ60B7I2QmwzpA0WAzXVWRlceNkpQj2inVdWiNCqcBmiyHyMQ/wGRsJ+YFKkgTjCy9NPrtWuFtZOvxnmZKaE3/DYh4tEFtFRtHSO1LcClO5gUVMisO2VQnHEMSz+StJLPa0xWWW6zE9CwG4q39c4BiM4Cnc6tUuAqy4WQBpGbCG80w9Kl+Ql6Z7Lm/Q9JLkJPsqJ9Yrp8Wf1igwtIM6I1VjjXlpbfP97TDX/ab8WIoNn02Bvugb5MSX+49pWRcHblqS8NEc4BR5aWJB3hFGzO+20oUn62WyYwowZOkC0QGg/5TtE349URmlhrre95vFdQpou1I9QqMC46BCpS29bEPL5JJ4I=
install: true
before_script:
- docker --version
- make --version
script:
  - make ARCH=${ARCH} DISTRIB=${DISTRIB} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} DISTRIB=${DISTRIB} push
after_script:
- docker logout
- make clean
